CMS.Website/Areas/Admin/Pages/Account/Create.cshtml.cs
using System;
using AutoMapper;
using CMS.Data.DataEntity;
using CMS.Data.ModelsDTO;
using CMS.Services.RepositoriesBase;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CMS.Website.Logging;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CMS.Website.Areas.Admin.Pages.Account
{
    public class CreateModel : PageModel
    {
        private readonly CmsContext _context;
        private readonly IRepositoryWrapper _repositoryWrapper;
        private readonly IMapper _maper;
        private readonly ILoggerManager _logger;
        private readonly UserManager<IdentityUser> _userManager;

        public CreateModel(CmsContext context, IRepositoryWrapper repositoryWrapper, IMapper mapper, ILoggerManager logger, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _repositoryWrapper = repositoryWrapper;
            _maper = mapper;
            _logger = logger;
            _userManager = userManager;
        }

        public async Task<IActionResult> OnGet()
        {
            var lstRole = await _repositoryWrapper.AspNetUsers.AspNetRolesGetAll();
            BindingListRole  =lstRole.Select(a =>
                new SelectListItem
                {
                    Value = a.Id.ToString(),
                    Text = a.Name
                }).ToList();

            return Page();
        }

        [BindProperty]
        public AspNetUserInfoDTO CreateNewUser { get; set; }

        //[BindProperties]
        //public  RoleId { get; set; }
        
        public List<SelectListItem> BindingListRole { get; set; }
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                await OnGet();
                return Page();
            }

            var userExists = _context.AspNetUsers.FirstOrDefault(p => p.UserName == CreateNewUser.AspNetUsers.Email);
            if (userExists != null)
            {
                ModelState.AddModelError("",$"Đã tồn tại tài khoản {CreateNewUser.AspNetUsers.Email}");
            }
            else
            {
                var user = new IdentityUser { UserName = CreateNewUser.AspNetUsers.Email, Email = CreateNewUser.AspNetUsers.Email };
                try
                {
                    var result = await _userManager.CreateAsync(user, CreateNewUser.AspNetUsers.Password);
                    if (result.Succeeded)
                    {
                        //Insert new Profilers
                        CreateNewUser.AspNetUserProfiles.UserId = user.Id;
                        await _repositoryWrapper.AspNetUsers.AspNetUserProfilesCreateNew(
                            _maper.Map<AspNetUserProfiles>(CreateNewUser.AspNetUserProfiles));
                        //Insert new Role
                        //CreateNewUser.AspNetUserRoles.RoleId = RoleId;
                        CreateNewUser.AspNetUserRoles.UserId = user.Id;
                        await _repositoryWrapper.AspNetUsers.AspNetUserRolesCreateNew(
                            _maper.Map<AspNetUserRoles>(CreateNewUser.AspNetUserRoles));
                    }
                }
                catch
                { }
            }
            return RedirectToPage("./Index");
        }
    }
}

CMS.Website/Areas/Admin/Pages/Advertising/AdvertisingList.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CMS.Data.DataEntity;
using CMS.Services.RepositoriesBase;
using CMS.Website.Logging;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;

namespace CMS.Website.Areas.Admin.Pages.Advertising
{
    public class AdvertisingListModel : PageModel
    {
        private readonly CmsContext _context;
        private readonly IRepositoryWrapper _repositoryWrapper;
        private readonly IMapper _maper;
        private readonly ILoggerManager _logger;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IHostingEnvironment _env;
        public AdvertisingListModel(CmsContext context, IRepositoryWrapper repositoryWrapper, IMapper mapper, ILoggerManager logger,
          UserManager<IdentityUser> userManager, IHostingEnvironment env)
        {
            _context = context;
            _repositoryWrapper = repositoryWrapper;
            _maper = mapper;
            _logger = logger;
            _userManager = userManager;
            _env = env;
        }
        public List<CMS.Data.DataEntity.Advertising> ListAdvertising;
        public async Task<IActionResult> OnGetAsync(int id)
        {
            var AdBlock = await _repositoryWrapper.Advertising.AdvertisingBlockGetById(id);
            
            ViewData["BlockId"] = id;
            ListAdvertising = await _repositoryWrapper.Advertising.AdvertisingGetByAdvertisingBlockId(id);
            return Page();
        }

        public async Task<IActionResult> OnGetDelete(int? Id, int? AdvertisingBlockId)
        {
            if (Id == null)
            {
                return NotFound();
            }
            else
            {
                var article = await _context.Advertising.FindAsync(Id);
                if (article != null)
                {
                    await _repositoryWrapper.Advertising.AdvertisingDelete(Id ?? 0);
                }
            }
            return Redirect("/Admin/Advertising/AdvertisingList/" + AdvertisingBlockId.ToString());
        }
    }
}

CMS.Website/Areas/Admin/Pages/Advertising/Create.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CMS.Data.DataEntity;
using CMS.Services.RepositoriesBase;
using CMS.Website.Logging;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace CMS.Website.Areas.Admin.Pages.Advertising
{
    public class CreateModel : PageModel
    {
        private readonly CmsContext _context;
        private readonly IRepositoryWrapper _repositoryWrapper;
        private readonly IMapper _maper;
        private readonly ILoggerManager _logger;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IHostingEnvironment _env;
        public CreateModel(CmsContext context, IRepositoryWrapper repositoryWrapper, IMapper mapper, ILoggerManager logger,
          UserManager<IdentityUser> userManager, IHostingEnvironment env)
        {
            _context = context;
            _repositoryWrapper = repositoryWrapper;
            _maper = mapper;
            _logger = logger;
            _userManager = userManager;
            _env = env;
        }
        [BindProperty]
        public CMS.Data.DataEntity.Advertising Advertising { get; set; }
        public int AdBlockId { get; set; }
        public async Task<IActionResult> OnGetAsync(int AdBlock, int? id)
        {
            AdBlockId = AdBlock;
            ViewData["AdBlockId"] = AdBlock;
            if (id == null)
            {
                return Page();
            }
            var result = await _repositoryWrapper.Advertising.FirstOrDefaultAsync(p => p.Id == id);
            if (result == null)
            {
                return NotFound();
            }
            else
            {
                Advertising = result;
            }
           
            return Page();
        }
        public async Task<IActionResult> OnPostSaveAsync(IEnumerable<IFormFile> mainimages)
        {
            //if (!ModelState.IsValid)
            //{
            //    return Page();
            //}
            Advertising.Active = bool.Parse(string.IsNullOrEmpty(Request.Form["chkActive"]) ? "False" : "True");            
            if (Advertising.Id == 0)
            {
                Advertising.Id = await _repositoryWrapper.Advertising.AdvertisingInsert(Advertising, _userManager.GetUserId(User), _env);
            }

            if (Advertising.Id != 0)
            {
                await _repositoryWrapper.Advertising.AdvertisingUpdate(Advertising, _userManager.GetUserId(User), mainimages, _env);
            }
            return Redirect("./AdvertisingList/" + Advertising.AdvertisingBlockId.ToString());
        }

        public IActionResult OnPostCancel(int id)
        {
            return Redirect("./AdvertisingList/" + Advertising.AdvertisingBlockId.ToString());
        }

    }
}

CMS.Website/Areas/Admin/Pages/Advertising/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using CMS.Data.DataEntity;
using CMS.Data.ModelsDTO;
using CMS.Services.RepositoriesBase;
using CMS.Website.Logging;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.Globalization;
using System.Web;
using CMS.Data.ModelsStore;
using CMS.Data.ModelFilter;

namespace CMS.Website.Areas.Admin.Pages.Advertising
{
    public class IndexModel : PageModel
    {
        private readonly CmsContext _context;
        private readonly IRepositoryWrapper _repositoryWrapper;
        private readonly IMapper _maper;
        private readonly ILoggerManager _logger;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IHostingEnvironment _env;
        public IndexModel(CmsContext context, IRepositoryWrapper repositoryWrapper, IMapper mapper, ILoggerManager logger,
          UserManager<IdentityUser> userManager, IHostingEnvironment env)
        {
            _context = context;
            _repositoryWrapper = repositoryWrapper;
            _maper = mapper;
            _logger = logger;
            _userManager = userManager;
            _env = env;
        }
        public List<AdvertisingBlock> ListAdvertisingBlocks;
        public async Task<IActionResult> OnGetAsync(bool isMobile)
        {
            ListAdvertisingBlocks = await _repositoryWrapper.Advertising.AdvertisingBlockGetAll(isMobile);
            return Page();
        }
    }
}

CMS.Website/Areas/Admin/Pages/Article/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using CMS.Data.DataEntity;
using CMS.Data.ModelsDTO;
using CMS.Services.RepositoriesBase;
using CMS.Website.Logging;
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.Globalization;
using System.Web;

namespace CMS.Website.Areas.Admin.Pages.Article
{
    public class CreateModel : PageModel
    {
        private readonly CmsContext _context;
        private readonly IRepositoryWrapper _repositoryWrapper;
        private readonly IMapper _maper;
        private readonly ILoggerManager _logger;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IHostingEnvironment _env;

        public CreateModel(CmsContext context, IRepositoryWrapper repositoryWrapper, IMapper mapper, ILoggerManager logger,
            UserManager<IdentityUser> userManager, IHostingEnvironment env)
        {
            _context = context;
            _repositoryWrapper = repositoryWrapper;
            _maper = mapper;
            _logger = logger;
            _userManager = userManager;
            _env = env;
        }
        
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                Article = new ArticleDTO();
                Article.Description = "(NXD) - ";
                return Page();
            }

            var result = await _repositoryWrapper.Article.FirstOrDefaultAsync(p => p.Id == id);
            if (result == null)
            {
                return NotFound();
            }
            else
            {
                Article = _maper.Map<ArticleDTO>(result);
                Article.Content = HttpUtility.HtmlDecode(Article.Content);
            }
            return Page();            
        }

        [BindProperty]
        public ArticleDTO Article { get; set; }
        public int? ArticleId { get; set; }
        public bool IsTopArticleCategory { get; set; } = false;
        public bool IsTopArticleCategoryParent { get; set; } = false;
        public int ArticleStatusId { get; set; } = 0;


        public ArticleCategoryBinding ArticleCategory { get; set; }

        public async Task<IActionResult> OnPostSaveAsync(IEnumerable<IFormFile> mainimages)
        {
            if (!ModelState.IsValid)
            {               
                return Page();
            }

            if (Article.Id == null)
            {                
                Article.Id = await _repositoryWrapper.Article.ArticleInsert(_maper.Map<Data.DataEntity.Article>(Article), _userManager.GetUserId(User), _env, ArticleStatusId);
            }

            if (Article.Id != null)
            {
                await _repositoryWrapper.Article.ArticleUpdate(_maper.Map<Data.DataEntity.Article>(Article), _userManager.GetUserId(User), mainimages, _env, ArticleStatusId);

                IsTopArticleCategory = bool.Parse(string.IsNullOrEmpty(Request.Form["chkTopArticleCategory"]) ? "False" : "True");
                IsTopArticleCategoryParent = bool.Parse(string.IsNullOrEmpty(Request.Form["chkTopArticleCategoryParent"]) ? "False" : "True");
                
                if (IsTopArticleCategory == true)
                {
                    _repositoryWrapper.Article.ArticleTopCategorySave(Article.Id.Value);
                }
                if (IsTopArticleCategoryParent == true)
                {
                    _repositoryWrapper.Article.ArticleTopParentCategorySave(Article.Id.Value);
                }
            }

            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostPublishAsync(IEnumerable<IFormFile> mainimages)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (User.IsInRole("Quản trị hệ thống"))
            {
                ArticleStatusId = 2;
            }
            if (!User.IsInRole("Quản trị hệ thống"))
            {
                ArticleStatusId = 1;
            }

            if (Article.Id == null)
            {
                Article.Id = await _repositoryWrapper.Article.ArticleInsert(_maper.Map<Data.DataEntity.Article>(Article), _userManager.GetUserId(User), _env, ArticleStatusId);
            }

            if (Article.Id != null)
            {
                await _repositoryWrapper.Article.ArticleUpdate(_maper.Map<Data.DataEntity.Article>(Article), _userManager.GetUserId(User), mainimages, _env, ArticleStatusId);

                IsTopArticleCategory = bool.Parse(string.IsNullOrEmpty(Request.Form["chkTopArticleCategory"]) ? "False" : "True");
                IsTopArticleCategoryParent = bool.Parse(string.IsNullOrEmpty(Request.Form["chkTopArticleCategoryParent"]) ? "False" : "True");

                if (IsTopArticleCategory == true)
                {
                    _repositoryWrapper.Article.ArticleTopCategorySave(Article.Id.Value);
                }
                if (IsTopArticleCategoryParent == true)
                {
                    _repositoryWrapper.Article.ArticleTopParentCategorySave(Article.Id.Value);
                }
            }

            return RedirectToPage("./Index");
        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("./Index");
        }

        public async void AddnewData()
        {
            Article.Id = await _repositoryWrapper.Article.ArticleInsert(_maper.Map<Data.DataEntity.Article>(Article), _userManager.GetUserId(User), _env, 2);
        }

        public async void UpdateData(IEnumerable<IFormFile> mainimages)
        {
            await _repositoryWrapper.Article.ArticleUpdate(_maper.Map<Data.DataEntity.Article>(Article), _userManager.GetUserId(User), mainimages, _env, 2);
        }

        public JsonResult OnGetArticleCategory(int? id)
        {
            var output = from e in _context.ArticleCategory
                         where (id.HasValue ? e.ParentId == id : e.ParentId == null)
                            select new
                            {
                                id = e.Id,
                                Name = e.Name,
                                hasChildren = (from q in _context.ArticleCategory
                                               where (q.ParentId == e.Id)
                                               select q
                                               ).Count() > 0
                            };

            return new JsonResult(output);
        }

        #region class
        public class ArticleCategoryBinding
        {
            public int ArticleCategoryIds { get; set; }
            public string Name { get; set; }
        }
        #endregion
    }
}

CMS.Website/Areas/Admin/Pages/Advertising/Create.cshtml
@page 
@model CMS.Website.Areas.Admin.Pages.Advertising.CreateModel
@{
    ViewData["Title"] = "Chỉnh sửa quảng cáo";
    Layout = "~/Pages/Shared/_LayoutAdmin.cshtml";    
}

<style type="text/css">
    .image-preview-main {
        position: relative;
        vertical-align: top;
        height: auto;
        width: 100%;
    }

    .image-preview-main-db {
        position: relative;
        vertical-align: top;
        height: auto;
        width: 100%;
    }
</style>
<!-- Main-body start -->
<div class="main-body">
    <div class="page-wrapper">
        <!-- Page-header start -->
        <div class="page-header">
            <div class="row align-items-end">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <div class="d-inline">
                            <h4>Cập nhật quảng cáo</h4>
                            <span>Thêm mới, chỉnh sửa quảng cáo</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">
                                <a href="/Admin"> <i class="feather icon-home"></i> </a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="/Admin/Advertising/Index">quảng cáo</a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#!">Cập nhật quảng cáo</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page-header end -->
        <!-- Page body start -->
        <div class="page-body">
            <div class="row">
                <div class="col-sm-12">
                    <!-- Basic Form Inputs card start -->
                    <div class="card">
                        <div class="card-block">
                            <h4 class="sub-title">Nội dung mô tả</h4>
                            <form method="post">
                                <input type="hidden" class="form-control" asp-for="Advertising.Id">
                                <input type="hidden" class="form-control" asp-for="Advertising.AdvertisingBlockId" value="@ViewData["AdBlockId"]">
                                <div class="form-group row">
                                    <div class="col-sm-8">
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Tên quảng cáo</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" asp-for="Advertising.Title" placeholder="Nhập tên quảng cáo">
                                                <span asp-validation-for="Advertising.Title" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Đường link</label>
                                            <div class="col-sm-10">
                                                <input type="text" class="form-control" asp-for="Advertising.Url" placeholder="Nhập link">
                                                <span asp-validation-for="Advertising.Url" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Thứ tự hiện thị</label>
                                            <div class="col-sm-10">
                                                <input type="number" class="form-control" asp-for="Advertising.Sort" placeholder="">
                                                <span asp-validation-for="Advertising.Sort" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Kích thước ngang (px)</label>
                                            <div class="col-sm-10">
                                                <input type="number" class="form-control" asp-for="Advertising.Width" placeholder="">
                                                <span asp-validation-for="Advertising.Width" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Kích thước dọc (px)</label>
                                            <div class="col-sm-10">
                                                <input type="number" class="form-control" asp-for="Advertising.Height" placeholder="">
                                                <span asp-validation-for="Advertising.Height" class="text-danger"></span>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Ngày giờ đăng</label>
                                            <div class="col-sm-4">
                                                @(Html.Kendo().DateTimePickerFor(m => m.Advertising.StartDate)
                                                    .HtmlAttributes(new { style = "width: 250px;" })
                                                    .Value(DateTime.Now)
                                                    .Culture("vi-VN")
                                                    .Format("dd/MM/yyyy HH:mm"))
                                                <span asp-validation-for="Advertising.StartDate" class="text-danger"></span>
                                            </div>
                                            <label class="col-sm-3 col-form-label" style="text-align: right;">Ngày kết thúc</label>
                                            <div class="col-sm-3">
                                                <div style="float: right">
                                                    @(Html.Kendo().DateTimePickerFor(m => m.Advertising.EndDate)
                                                    .HtmlAttributes(new { style = "width: 250px;" })
                                                    .Value(DateTime.Now.AddYears(10))
                                                    .Culture("vi-VN")
                                                    .Format("dd/MM/yyyy HH:mm"))
                                                    <span asp-validation-for="Advertising.EndDate" class="text-danger"></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label"></label>
                                            <div class="col-sm-10">
                                                <input type="checkbox" name="chkActive" id="chkActive" />
                                                <label style="margin-right: 30px;">Cho đăng luôn</label>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Code</label>
                                            <div class="col-sm-10">
                                                <textarea type="text" style="height: 150px;" class="form-control" asp-for="Advertising.Code" placeholder=""></textarea>
                                                <span asp-validation-for="Advertising.Code" class="text-danger"></span>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group row">
                                            <div class="col-md-12">
                                                @(Html.Kendo().Upload()
                                                    .Multiple(false)
                                                    .Name("mainimages")
                                                    .Messages(x => x.Select("chọn ảnh đại diện"))
                                                    .Events(e => e.Select("onSelectMain")
                                                    )
                                                )
                                                <div id="image_preview_main">
                                                    @{if (Model.Advertising != null && Model.Advertising.Image != null)
                                                        {
                                                            <img class="image-preview-main-db" src="/data/Advertising/mainimages/original/@Model.Advertising.Image" />
                                                        }
                                                        else
                                                        {

                                                        }
                                                    }
                                                </div>
                                                <span asp-validation-for="Advertising.Image" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group row" style="justify-content: center">
                                    <button type="submit" asp-page-handler="Save" class="btn btn-mat btn-primary"><i class="fa fa-save"></i>Lưu</button>
                                    <button type="submit" asp-page-handler="Cancel" asp-route-id="@Model.AdBlockId" class="btn btn-mat btn-warning"><i class="fa fa-times-circle"></i>Hủy bỏ</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- Basic Form Inputs card end -->
                </div>
            </div>
        </div>
        <!-- Page body end -->
    </div>
</div>

<script>

    function onDropDownSelect(e) {
        var dataitem = e.sender.dataItem(e.node);
        console.log(dataitem);
        if (dataitem.hasChildren) {
            e.preventDefault();
        }
    }
</script>

<script type="text/javascript">

    function onSelectMain(e) {
        var fileInfos = e.files;
        var wrapper = this.wrapper;

        fileInfos.forEach(function (fileInfo) {
            setTimeout(function () {
                addPreviewMain(fileInfo, wrapper);
            });
        });
    }

    function addPreviewMain(file, wrapper) {
        var raw = file.rawFile;
        var reader = new FileReader();

        if (raw) {
            reader.onloadend = function () {
                var preview = $("<img class='image-preview-main'>").attr("src", this.result);

                wrapper.find(".k-file[data-uid='" + file.uid + "'] .k-file-extension-wrapper")
                    .replaceWith(preview);
                $("#image_preview_main").html($("<img class='image-preview-main-db'>").attr("src", this.result));
            };
            reader.readAsDataURL(raw);
        }
    }
</script>
<script>
    function forgeryToken() {
        return kendo.antiForgeryTokens();
    }</script>